name: lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: checks
      run: |
        python -m pip install -r requirements.txt
        python -m autoflake --in-place --remove-all-unused-imports --remove-unused-variables --ignore-init-module --check -r streamable tests
        python -m black --check streamable/* tests/*
