name: typing

on:
  push:
    paths:
      - 'streamable'
      - 'tests'

jobs:
  mypy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: mypy
      run: |
        python -m pip install -r requirements.txt
        python -m mypy streamable tests
